### ISSUE TITLE
Last release failed

### ISSUE THREAD

**Issue by tekktrik** [FoamyGuy/Blinka_Displayio_PyGameDisplay#10]
Hey @FoamyGuy, noticed the last release to PyPI failed due to a weird version string being used.  I'll look into it but wanted to make a record before I forgot.

**Comment by bablokb** [comment]
Do you refer to the `0.0.0-auto.0` instead of the `0.0.0+auto.0`? I have an open pull-request so I could fix this as well.

**Comment by tekktrik** [comment]
Yes, but it also seems to have tried to publish to PyPI with a girt-based version.  Changing the version string you mentioned may fix it, but I think it needs slightly more work.

**Comment by FoamyGuy** [comment]
I believe this should be resolved now. Latest releases do appear to have made it to PyPi. Feel free to re-open or make a new issue if anyone has trouble getting the current from pypi still / again in the future.
